const express=require("express"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),{Pool}=require("pg"),crypto=require("crypto");
if(!process.env.DATABASE_URL||!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32)throw Error("Missing required private configuration");
const rateLimit=require("express-rate-limit");
const loginLimit=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:"draft-7",legacyHeaders:false});
const changeLimit=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:"draft-7",legacyHeaders:false});
const app=express();app.disable("x-powered-by");app.use(express.json({limit:"16kb"}));app.use("/setup",express.urlencoded({extended:false,limit:"4kb"}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined});
const PERMS=["CREATE_MEMBER","CREDIT_CASH","APPROVALS","MEMBERS","CREATE_ADMIN","ADMIN_PERMISSIONS"];
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS accounts(id BIGSERIAL PRIMARY KEY,full_name TEXT NOT NULL,phone TEXT,username TEXT UNIQUE NOT NULL,credential_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('MEMBER','FLEXIBLE','ADMIN')),must_change_credential BOOLEAN NOT NULL DEFAULT TRUE,linked_regular_id BIGINT REFERENCES accounts(id),active BOOLEAN NOT NULL DEFAULT TRUE,failed_logins INT NOT NULL DEFAULT 0,locked_until TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS admin_permissions(account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,permission TEXT NOT NULL,PRIMARY KEY(account_id,permission));CREATE TABLE IF NOT EXISTS security_events(id BIGSERIAL PRIMARY KEY,account_id BIGINT REFERENCES accounts(id),event_type TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);await pool.query("ALTER TABLE accounts ADD COLUMN IF NOT EXISTS failed_logins INT NOT NULL DEFAULT 0");await pool.query("ALTER TABLE accounts ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ");}
function issue(a){return jwt.sign({sub:String(a.id),role:a.role,credentialChangeOnly:a.must_change_credential},process.env.JWT_SECRET,{expiresIn:a.must_change_credential?"10m":"2h"})}
function valid(role,c){return role==="ADMIN"?typeof c==="string"&&c.length>=12&&c.length<=128:typeof c==="string"&&/^[0-9]{4}$/.test(c)}
function auth(req,res,next){try{const t=(req.headers.authorization||"").match(/^Bearer (.+)$/);if(!t)throw Error();req.claims=jwt.verify(t[1],process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:"Unauthorized"})}}
async function current(req,res,next){try{const q=await pool.query("SELECT id,role,active,must_change_credential FROM accounts WHERE id=$1",[req.claims.sub]);if(!q.rowCount||!q.rows[0].active||q.rows[0].role!==req.claims.role)return res.status(401).json({error:"Unauthorized"});req.account=q.rows[0];next()}catch(e){next(e)}}
function ready(req,res,next){if(req.account.must_change_credential)return res.status(403).json({error:"Credential change required"});next()}
app.get("/health",async(req,res)=>{try{await pool.query("SELECT 1");res.json({ok:true,service:"taimako-new-backend"})}catch{res.status(503).json({ok:false})}});
app.post("/auth/login",loginLimit,async(req,res,next)=>{try{const{username,credential}=req.body||{};if(typeof username!=="string"||username.length>64||typeof credential!=="string"||credential.length>128)return res.status(400).json({error:"Invalid request"});const q=await pool.query("SELECT * FROM accounts WHERE username=$1 AND active=TRUE",[username]);const a=q.rows[0];if(a?.locked_until&&new Date(a.locked_until)>new Date())return res.status(429).json({error:"Account temporarily locked"});const ok=await bcrypt.compare(credential,a?.credential_hash||"$2a$12$abcdefghijklmnopqrstuu8dqN6n.S3S1jB08ZQ8Oeq0P1m3ZyBni");if(!a||!ok){if(a)await pool.query("UPDATE accounts SET failed_logins=failed_logins+1,locked_until=CASE WHEN failed_logins+1>=5 THEN NOW()+INTERVAL '15 minutes' ELSE NULL END WHERE id=$1",[a.id]);return res.status(401).json({error:"Invalid credentials"})}await pool.query("UPDATE accounts SET failed_logins=0,locked_until=NULL WHERE id=$1",[a.id]);await pool.query("INSERT INTO security_events(account_id,event_type) VALUES($1,'LOGIN')",[a.id]);res.json({token:issue(a),role:a.role,mustChangeCredential:a.must_change_credential,fullName:a.full_name,username:a.username})}catch(e){next(e)}});
app.post("/auth/change-credential",changeLimit,auth,current,async(req,res,next)=>{try{const{currentCredential,newCredential}=req.body||{};if(!valid(req.account.role,newCredential)||typeof currentCredential!=="string")return res.status(400).json({error:"Invalid credential format"});const q=await pool.query("SELECT credential_hash FROM accounts WHERE id=$1",[req.account.id]);if(!await bcrypt.compare(currentCredential,q.rows[0].credential_hash))return res.status(401).json({error:"Invalid current credential"});if(currentCredential===newCredential)return res.status(400).json({error:"Choose a different credential"});await pool.query("UPDATE accounts SET credential_hash=$1,must_change_credential=FALSE WHERE id=$2",[await bcrypt.hash(newCredential,12),req.account.id]);await pool.query("INSERT INTO security_events(account_id,event_type) VALUES($1,'CREDENTIAL_CHANGED')",[req.account.id]);res.json({ok:true,loginAgain:true})}catch(e){next(e)}});
app.get("/auth/me",auth,current,ready,async(req,res)=>res.json({id:req.account.id,role:req.account.role}));
app.get("/setup",(_req,res)=>res.sendFile(require("path").join(__dirname,"setup-page.html")));
app.use("/setup",require("./bootstrap")(pool));
app.get("/recovery",(_req,res)=>res.sendFile(require("path").join(__dirname,"recovery-page.html")));
app.use("/recovery",require("./recovery")(pool));
app.get("/",(req,res)=>res.json({service:"TAIMAKO Cooperative New Backend",financialTransactions:false}));
app.use((e,req,res,next)=>{console.error("Request failed:",e.message);res.status(500).json({error:"Server error"})});
init().then(()=>app.listen(process.env.PORT||10000,"0.0.0.0",()=>console.log("TAIMAKO new backend listening"))).catch(e=>{console.error(e);process.exit(1)});
