const express=require("express");const bcrypt=require("bcryptjs");const jwt=require("jsonwebtoken");const {Pool}=require("pg");
const app=express();app.use(express.json());const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined});
const roles=["MEMBER","FLEXIBLE","ADMIN"];const perms=["CREATE_MEMBER","CREDIT_CASH","APPROVALS","MEMBERS","CREATE_ADMIN","ADMIN_PERMISSIONS"];
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS accounts(id BIGSERIAL PRIMARY KEY,full_name TEXT NOT NULL,phone TEXT,username TEXT UNIQUE NOT NULL,credential_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('MEMBER','FLEXIBLE','ADMIN')),must_change_credential BOOLEAN NOT NULL DEFAULT TRUE,linked_regular_id BIGINT REFERENCES accounts(id),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS admin_permissions(account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,permission TEXT NOT NULL,PRIMARY KEY(account_id,permission));`)}
function token(a){return jwt.sign({sub:String(a.id),role:a.role},process.env.JWT_SECRET,{expiresIn:"12h"})}
app.get("/health",async(req,res)=>{try{await pool.query("SELECT 1");res.json({ok:true,service:"taimako-new-backend"})}catch(e){res.status(503).json({ok:false})}});
app.post("/auth/login",async(req,res)=>{const{username,credential}=req.body||{};const q=await pool.query("SELECT * FROM accounts WHERE username=$1 AND active=TRUE",[username]);if(!q.rowCount||!await bcrypt.compare(String(credential||""),q.rows[0].credential_hash))return res.status(401).json({error:"Invalid credentials"});const a=q.rows[0];res.json({token:token(a),role:a.role,mustChangeCredential:a.must_change_credential,fullName:a.full_name,username:a.username})});
app.post("/auth/change-credential",async(req,res)=>{try{const h=(req.headers.authorization||"").replace(/^Bearer /,"");const p=jwt.verify(h,process.env.JWT_SECRET);const c=String(req.body?.newCredential||"");if((p.role==="MEMBER"||p.role==="FLEXIBLE")&&!/^\d{4}$/.test(c))return res.status(400).json({error:"PIN must be exactly 4 digits"});if(p.role==="ADMIN"&&c.length<4)return res.status(400).json({error:"Password must be at least 4 characters"});await pool.query("UPDATE accounts SET credential_hash=$1,must_change_credential=FALSE WHERE id=$2",[await bcrypt.hash(c,12),p.sub]);res.json({ok:true})}catch(e){res.status(401).json({error:"Unauthorized"})}});
app.get("/",(req,res)=>res.json({service:"TAIMAKO Cooperative New Backend",financialTransactions:false}));
const port=process.env.PORT||10000;init().then(()=>app.listen(port,"0.0.0.0",()=>console.log("TAIMAKO backend listening",port))).catch(e=>{console.error(e);process.exit(1)});
